### ISSUE TITLE
asebastudio (1.6 and 1.6.9) are crahing at startup connection to Thymio trough USB

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#267] opened 2018-10-03 14:30 UTC
when you try to open & close Aseba Studio lot of time it is happening 1 time over 2 (on Windows 10)

debug info:
Le thread 0xfa4 s'est arrêté avec le code 0 (0x0).
Exception non gérée à 0x00007FF640601A74 dans asebastudio.exe : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0x0000000000000040.
![image](https://user-images.githubusercontent.com/1000934/46417269-8b552600-c729-11e8-9fd5-3644df895956.png)

**Comment by cor3ntin** [comment] 2018-10-09 15:40
I was unable to reproduce anything of the sort :(

**Comment by cor3ntin** [comment] 2018-10-31 14:21
Fixed in #c7d7a9b

**Closed by cor3ntin** 2018-10-31 14:21 UTC
Labels: bug
