### ISSUE TITLE
No more control on graphs in Studio and time units

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#547] opened 2019-05-13 11:15 UTC
There are no more control on the graph in Studio (like pause/start, time window, save, erase) and the time unit is quite big (several thousands in a few seconds), before the time unit was second, I guess it's better for general purposes.

![image](https://user-images.githubusercontent.com/4930020/57617357-e92fd300-7580-11e9-8611-b5aa50719fee.png)

**Comment by mbonani** [comment] 2019-05-13 11:31
this is a duplicate of issues #379 and  #530

**Closed by mbonani** 2019-05-13 11:31 UTC
Labels: Studio, Wish
